#!/bin/bash
# Use this script to split a flac image into tracks

IMAGE_FILE=''
CUE_FILE=''

if [ $# -eq 0 ]; then
	IMAGE_FILE="$(ls | grep *.flac)"
	CUE_FILE="$(ls | grep *.cue)"

	if [ "x$IMAGE_FILE" == "x" ] || [ "x$CUE_FILE" == "x" ]; then
		echo ".flac or .cue not found"
		exit 1
	fi
else
	while [ "$1" ]; do
		if [[ "$1" =~ .*\.flac$ ]]; then
			IMAGE_FILE="$1"
		elif [[ "$1" =~ .*\.cue$ ]]; then
			CUE_FILE="$1"
		fi
		shift
	done
	if [ ! -f "$IMAGE_FILE" ] || [ ! -f "$CUE_FILE" ]; then
		echo ".flac or .cue not found"
		exit 2
	fi
fi


echo "[IMAGE] $IMAGE_FILE"
echo "[ CUE ] $CUE_FILE"

# Split image, encode to flac, and verify the encode
shnsplit -f "$CUE_FILE" -o "flac flac -8 -V -o %f -" -t "%n - %t" "$IMAGE_FILE"

# rename original image temporarily for next step
mv "$IMAGE_FILE" "${IMAGE_FILE}.original"

# Tag newly made files using cue
cuetag "$CUE_FILE" *.flac

# Rename the image back
mv "${IMAGE_FILE}.original" "$IMAGE_FILE"
