#!/bin/bash
# Use this script to split a flac image into tracks

IMAGE_FILE="$(ls | grep *.flac)"
CUE_FILE="$(ls | grep *.cue)"

if [ "x$IMAGE_FILE" == "x" ] || [ "x$CUE_FILE" == "x" ]; then
	echo ".flac or .cue not found"
	exit 1
fi

echo "[IMAGE] $IMAGE_FILE"
echo "[ CUE ] $CUE_FILE"

# Split image, encode to flac, and verify the encode
shnsplit -f "$CUE_FILE" -o "flac flac -8 -V -o %f -" -t "%n - %t" "$IMAGE_FILE"

# rename original image temporarily for next step
mv "$IMAGE_FILE" "x"

# Tag newly made files using cue
cuetag "$CUE_FILE" *.flac

# Rename the image back
mv "x" "$IMAGE_FILE"
